fixed log generation of trim and align
sherlyn99/mopp pull request #25
Opened 2024-05-12 22:29 UTC by ehaddad1

2024-05-12 22:31 UTC, ehaddad1 commented
the issue was that "create_folder" was being run after the .log file was generated, so .log got deleted. I fixed it by running "create_folder" before generating the .log file

2024-05-17 23:18 UTC, sherlyn99 requested changes

2024-05-17 23:18 UTC, sherlyn99 commented on mopp/modules/align.py
> -    create_folder(outdir_aligned)
thanks for identifying the issue! I think a simpler fix would be import `create_folder_without_clear` from `mopp.modules.utils` and then substitute all `create_folder` with `create_folder_without_clear`

2024-05-17 23:18 UTC, sherlyn99 commented on mopp/mopp.py
> +    outdir_cat = Path(output_dir)
this will be done in `trim_files` in `trim.py`

2024-10-21 20:37 UTC, closed without merging